### ISSUE TITLE
How do we test it.

### ISSUE THREAD

**Issue by mshoaibdev** [terrylinooo/shieldon#16]
First of all, thank you for the library, I installed it in my Laravel application, now I am looking to test it with flood requests. any tool which you recommend.

**Comment by terrylinooo** [comment]
Hello.

You can use try the free web performance testing tool provided by Mircosoft's Azure.

I just try a test for you, target: https://shieldon.io

![image](https://user-images.githubusercontent.com/11989371/70598341-95c05900-1c25-11ea-8d5a-6d91f5aab730.png)

My setting:

![image](https://user-images.githubusercontent.com/11989371/70598482-e9cb3d80-1c25-11ea-856a-a8b175ca66af.png)

Because I have set the online session limit to 100, so this dialog will be displayed to queued sessions.

![image](https://user-images.githubusercontent.com/11989371/70598290-74f80380-1c25-11ea-947b-efe58c392d4f.png)

Notification:

![image](https://user-images.githubusercontent.com/11989371/70598778-8f7eac80-1c26-11ea-8c52-138fa4b834e8.png)

You can try any kind of tool and look up your CPU usage, RAM.
Hope this help.
