### ISSUE TITLE
Instalation on Yii2 Advanced

### ISSUE THREAD

**Issue by biladina** [terrylinooo/shieldon#25]
hi, I am working with yii2 with many sub modules application like [yii2-advanced](https://github.com/yiisoft/yii2-app-advanced) template..

so my question is, if I install this app, it must be install to every sub module (like in [yii2-advanced](https://github.com/yiisoft/yii2-app-advanced), its have 2 sub module, frontend and backend) or just install to one of sub module to cover whole sub modules??

**Comment by terrylinooo** [comment]
Edit `index.php` located at `frontend/web`

Before this line:
```
require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';
```
Add:
```php
if (isset($_SERVER['REQUEST_URI'])) {

    // Notice that this directory must be writable.
    $firewallstorage = __DIR__ . '/../runtime/shieldon';

    $firewall = new \Shieldon\Firewall($firewallstorage);
    $firewall->restful();
    $firewall->run();
}
```

Create the entry for the control panel please see:
https://shieldon.io/en/guide/yii.html

**Comment by biladina** [comment]
so, if I install shieldon in frontend, it will covers to other sub module (backend, etc), or just cover the frontend sub module??

**Comment by terrylinooo** [comment]
Just use it on frontend. Because the main purpose to use this library is to protect your website from bad crawlers and other bad behavior such as vulnerability scanning, brute-force attack, etc... Not for backend. Be sure to set the excluded list for your backend URLs. 

![image](https://user-images.githubusercontent.com/11989371/88148649-7f559380-cc31-11ea-8593-fa9802fb2a7c.png)

**Comment by biladina** [comment]
ok, I got it..

one more, is it possible to use shieldon in yii2 without enable prettyurl??
